### ISSUE TITLE
How to stop events emitting after component is destroyed

### ISSUE THREAD

**Issue by juanfabrega** [Orlandster/vue-typed-js#5]
Hey, love the library! 

After implenting it on a project, I noticed that the module is emitting events in a loop even after the component which renders it is destroyed. How can I stop event triggers after I'm no longer on the page that features VueTypedJs?

Thanks!

**Comment by Orlandster** [comment]
Hey, Thanks for contributing to the project. This seems to be a bug. I will implement a destroy hook during the next week, which kills the typed.js instance.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by juanfabrega** [comment]
Ok sounds good. If I have time I’d be happy to contribute a PR for this.
Will give it a shot.
