### ISSUE TITLE
showCursor property is not reactive

### ISSUE THREAD

**Issue by LeCoupa** [Orlandster/vue-typed-js#6]
Hey! :)
Setting the showCursor property to `true` and then to `false` does not remove the cursor. Is that the expected behaviour? Is there a way to make it reactive?

**Comment by Nfinished** [comment]
Is the entire property broken? I'm having difficulty getting the cursor to show at all.

**Comment by robfr77** [comment]
I'm having the same issue - can't change it directly since a ```prop``` so I set it equal to a reactive property but setting it to ```false``` it did not stop the flashing cursor. Did you figure this out or are you open for help on this? Thanks
