### ISSUE TITLE
i need help in the event 

### ISSUE THREAD

**Issue by gabrielbarretosantoos** [Orlandster/vue-typed-js#9]
Hey, guys.

I need help to subscribe to the event, as I currently use a lib to perform string translation.

I make the request via router, in which I change the router and it does the simulated translation, however the strings inside the vue-typed are not translated, only when I give a reload on the page. I need help to carry out this simuntaneo translation, without needing to reload the page.

Here is a snippet of code so you can see my problem:

`<vue-typed-js
                        :strings="[$t('title_site.span_design'),$t('title_site.span_manage'),$t('title_site.span_dev')]"
                        :backSpeed="100"
                        :typeSpeed="100"
                        :backDelay="1000">
                        <h1>{{ $t('title_site.message_think')}}<br/>
                            {{ $t('title_site.aux_let') }}
                            <span class="typing"></span>
                            {{ $t('title_site.aux_us') }}
                        </h1>
                    </vue-typed-js>`

Thank you and I'll be waiting.

**Comment by Orlandster** [comment]
Hey,
Thanks for your question. It seems like you will need to reinitialize your component after the language got switched. I will solve it for you, if you provide me a `jsfiddle` or some kind of playground where I can test it.

**Comment by gabrielbarretosantoos** [comment]
Hi brother, thanks for the answer. 
I'm problem to send via jsfiddle, I will anexo for here the codes. I'm use the lib vue-i18n (http://kazupon.github.io/vue-i18n/) i try 

**HOME.vue**

`<vue-typed-js
                        :strings="[$t('title_site.span_design'),$t('title_site.span_manage'),$t('title_site.span_dev')]"
                        :backSpeed="100"
                        :typeSpeed="100"
                        :backDelay="1000">
                        <h1>{{ $t('title_site.message_think')}}<br/>
                            {{ $t('title_site.aux_let') }}
                            <span class="typing"></span>
                            {{ $t('title_site.aux_us') }}
                        </h1>
                    </vue-typed-js>`

I18N.js

`Vue.use(VueI18n)

const i18n = new VueI18n({
    messages
});

export default i18n`

MESSAGE.js

`export default {
pt:{
    title.site:{
            span_design: 'o design',
            span_manage: 'a gestão',
            span_dev: 'o desenvolvimento',
                  }
       }
            
}`

MAIN.js

`new Vue({
    el: '#app',
    router,
    i18n,
    render: h => h(App)
});`**

i tried simulate my scenario, i expect you understand hehehe.

my e-mail is gabrielbarretosantoos@gmail.com if you do not understand, could you send me an email?

and one more time, thanks brother!

**Comment by Orlandster** [comment]
@gabrielbarretosantoos I've created an example with a quick fix for your problem. You can find it here: https://github.com/Orlandster/vue-typed-i18n-fix

Just clone and try it out. In the meantime I will work on a better fix.

**Comment by gabrielbarretosantoos** [comment]
@Orlandster This quick fix solution my problem. Thanks a lot,  i'll waiting, hehe
